/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TechSkillsRouteImport } from './routes/tech-skills'
import { Route as SoftSkillsRouteImport } from './routes/soft-skills'
import { Route as SocialRouteImport } from './routes/social'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MailsRouteImport } from './routes/mails'
import { Route as InterviewRouteImport } from './routes/interview'
import { Route as ConnectorsRouteImport } from './routes/connectors'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TechSkillsRoute = TechSkillsRouteImport.update({
  id: '/tech-skills',
  path: '/tech-skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SoftSkillsRoute = SoftSkillsRouteImport.update({
  id: '/soft-skills',
  path: '/soft-skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MailsRoute = MailsRouteImport.update({
  id: '/mails',
  path: '/mails',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewRoute = InterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectorsRoute = ConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/connectors': typeof ConnectorsRoute
  '/interview': typeof InterviewRoute
  '/mails': typeof MailsRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/social': typeof SocialRoute
  '/soft-skills': typeof SoftSkillsRoute
  '/tech-skills': typeof TechSkillsRoute
  '/tools': typeof ToolsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/connectors': typeof ConnectorsRoute
  '/interview': typeof InterviewRoute
  '/mails': typeof MailsRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/social': typeof SocialRoute
  '/soft-skills': typeof SoftSkillsRoute
  '/tech-skills': typeof TechSkillsRoute
  '/tools': typeof ToolsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/connectors': typeof ConnectorsRoute
  '/interview': typeof InterviewRoute
  '/mails': typeof MailsRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/social': typeof SocialRoute
  '/soft-skills': typeof SoftSkillsRoute
  '/tech-skills': typeof TechSkillsRoute
  '/tools': typeof ToolsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/connectors'
    | '/interview'
    | '/mails'
    | '/profile'
    | '/sitemap.xml'
    | '/social'
    | '/soft-skills'
    | '/tech-skills'
    | '/tools'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/connectors'
    | '/interview'
    | '/mails'
    | '/profile'
    | '/sitemap.xml'
    | '/social'
    | '/soft-skills'
    | '/tech-skills'
    | '/tools'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/connectors'
    | '/interview'
    | '/mails'
    | '/profile'
    | '/sitemap.xml'
    | '/social'
    | '/soft-skills'
    | '/tech-skills'
    | '/tools'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ConnectorsRoute: typeof ConnectorsRoute
  InterviewRoute: typeof InterviewRoute
  MailsRoute: typeof MailsRoute
  ProfileRoute: typeof ProfileRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SocialRoute: typeof SocialRoute
  SoftSkillsRoute: typeof SoftSkillsRoute
  TechSkillsRoute: typeof TechSkillsRoute
  ToolsRoute: typeof ToolsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech-skills': {
      id: '/tech-skills'
      path: '/tech-skills'
      fullPath: '/tech-skills'
      preLoaderRoute: typeof TechSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soft-skills': {
      id: '/soft-skills'
      path: '/soft-skills'
      fullPath: '/soft-skills'
      preLoaderRoute: typeof SoftSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mails': {
      id: '/mails'
      path: '/mails'
      fullPath: '/mails'
      preLoaderRoute: typeof MailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview': {
      id: '/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof InterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connectors': {
      id: '/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof ConnectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ConnectorsRoute: ConnectorsRoute,
  InterviewRoute: InterviewRoute,
  MailsRoute: MailsRoute,
  ProfileRoute: ProfileRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SocialRoute: SocialRoute,
  SoftSkillsRoute: SoftSkillsRoute,
  TechSkillsRoute: TechSkillsRoute,
  ToolsRoute: ToolsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
